# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-31 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhizhu_proxy', '0002_auto_20181031_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='wangba',
            name='wb_for',
            field=models.ForeignKey(max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='zhizhu_proxy.City', verbose_name='属于哪个区'),
        ),
        migrations.AlterField(
            model_name='wangba',
            name='wb',
            field=models.CharField(max_length=32, null=True, verbose_name='网吧名称'),
        ),
    ]
