# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_name', models.CharField(max_length=128, null=True, verbose_name='标签名字')),
                ('tags_create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Xiaohua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_id', models.IntegerField(null=True, unique=True)),
                ('x_title', models.CharField(max_length=256, verbose_name='笑话标题')),
                ('x_create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('x_source', models.CharField(max_length=128, null=True, verbose_name='爬取来源')),
                ('x_img_url', models.TextField(verbose_name='图片链接')),
                ('x_text', models.TextField(null=True, verbose_name='笑话内容')),
                ('x_img', models.ImageField(null=True, upload_to='', verbose_name='笑话图片')),
                ('x_html_text', models.TextField(null=True, verbose_name='html文本')),
                ('x_tags', models.ManyToManyField(blank=True, to='xiaohua_spider.Tags', verbose_name='标签集合')),
            ],
            options={
                'verbose_name': '笑话信息',
                'verbose_name_plural': '笑话信息',
            },
        ),
    ]
