# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hongchang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=32, null=True, verbose_name='西城红场'),
        ),
    ]
