# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-12 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuluOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leibie', models.CharField(max_length=30, verbose_name='类别')),
                ('url', models.CharField(max_length=120, verbose_name='链接')),
                ('title', models.CharField(max_length=240, null=True, verbose_name='标题')),
                ('jianjie', models.TextField(null=True, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='MuluTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leibie', models.CharField(max_length=30, verbose_name='类别')),
                ('url', models.CharField(max_length=120, verbose_name='链接')),
                ('title', models.CharField(max_length=240, null=True, verbose_name='标题')),
                ('jianjie', models.TextField(null=True, verbose_name='标题')),
                ('waijian_muluone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazhongsite.MuluOne')),
            ],
        ),
        migrations.CreateModel(
            name='NewsOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('timeup', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('textone', models.TextField(verbose_name='正文')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('waijian_muluone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazhongsite.MuluOne')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('timeup', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('textone', models.TextField(verbose_name='正文')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('waijian_mulutwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazhongsite.MuluTwo')),
            ],
        ),
        migrations.CreateModel(
            name='Otherone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='预留字段(charm)')),
                ('textone', models.TextField(verbose_name='预留字段(Text)')),
            ],
        ),
    ]
