# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-13 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazhongsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muluone',
            options={'verbose_name': '主导航', 'verbose_name_plural': '主导航'},
        ),
        migrations.AlterModelOptions(
            name='mulutwo',
            options={'verbose_name': '二级导航', 'verbose_name_plural': '二级导航'},
        ),
        migrations.AlterModelOptions(
            name='newsone',
            options={'verbose_name': '主导航对应信息', 'verbose_name_plural': '主导航对应信息'},
        ),
        migrations.AlterModelOptions(
            name='newstwo',
            options={'verbose_name': '二级导航对应信息', 'verbose_name_plural': '二级导航对应信息'},
        ),
        migrations.AlterModelOptions(
            name='otherone',
            options={'verbose_name': '其他表', 'verbose_name_plural': '其他表'},
        ),
        migrations.AlterField(
            model_name='muluone',
            name='jianjie',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='mulutwo',
            name='jianjie',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
    ]
