# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-19 08:58
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hazhongsite', '0002_auto_20180913_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsone',
            name='textone',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='newstwo',
            name='textone',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
