# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazhongsite', '0002_muluone_image_muluone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muluone',
            name='image_MuluOne',
            field=models.ImageField(null=True, upload_to='./images'),
        ),
    ]
